#!/bin/bash
# wallpaper
# Created Fri Feb  8 07:14:33 AKST 2019
# Copyright (C) 2019 by Raymond E. Marcil <marcilr@gmail.com>
#
# Script to set backfground wallpaper under Xfce v4.12
#
# $ xfce4-panel --version
# xfce4-panel 4.12.1 (Xfce 4.12)
# ...
# $
#
# "Again, the default Xfce wallpaper is not bad at all.
# But you can change the wallpaper to something that matches
# with your icons and themes.
#
# To change wallpapers in Xfce, right click on the desktop
# and click on Desktop Settings. You can change the desktop
# background from your custom collection or the defaults
# one given.
#
# Right click on the desktop and click on Desktop Settings.
# Choose Background from the folder option, and choose any
# one of the default backgrounds or a custom one."
# --4 Ways You Can Make Xfce Look Modern and Beautiful
#   Last updated July 25, 2018 By Ambarish Kumar 35 Comments
#   https://itsfoss.com/customize-xfce/
#
#
# Fri Feb  8 07:47:32 AKST 2019
# =============================
# Updated and got this script operational for Xfce 4.12
# Under Debian Stretch 9.7 amd64  running under VirtualBox.
#
# Initially anually set the wallpaper as described above.
# Migrated wallaper library to Xfce's standard
# /usr/share/backgrounds/ location:
#
# cd /usr/share
# mv backgrounds/ backgrounds-ORIG-20190208
# ln -s /usr/local/wallpaper /usr/share/backgrounds
#
#
# Links
# =====
# Returning Values from Bash Functions
# by Mitch Frazier on September 11, 2009
# https://www.linuxjournal.com/content/return-values-bash-functions
#
# set the desktop wallpaper under Xfce4
# https://ubuntuincident.wordpress.com/2015/03/08/set-the-desktop-wallpaper-under-xfce4/
#

# =============
# Configuration
# =============

#
# Enable debugging by assigning DEBUG to any value
# i.e. To display just comment out DEBUG.
#
DEBUG=true

# Directory with wallpaper to randomly select and set
WALLPAPERDIR=~/.wallpaper

# Binaries
LS=/bin/ls
SHUF=/usr/bin/shuf
SORT=/usr/bin/sort
TAIL=/usr/bin/tail


# =========
# Functions
# =========


#
# debug()
#
debug() {
  [[ ! -z "${DEBUG}" ]] && echo "debug() ${1}"
}


#
# random()
# Get a random image for the WALLPAPERDIR directory
#
random() {

  #debug "random() start"

  #
  # NOTE: Could update ls to find below for recursive operation
  #       on wallpaper directory.
  #
  #${LS} ${WALLPAPERDIR}/*.{gif,jpg,jpeg,png} | ${SORT} -R | ${TAIL} -$N | while read FILE; do
  #  debug "random() FILE: ${FILE}"
  #done

  FILE=`${LS} ${WALLPAPERDIR} | ${SHUF} | ${TAIL} --lines=1`

  debug "random() FILE: ${FILE}"
  #debug "random() end"

}


# =========
# Main
# =========

debug "main: *** START ***"


# Query all properties that end with “last-image“:
xfconf-query -c xfce4-desktop -l | grep "last-image$" | while read IMAGE; do
  debug "main: IMAGE: $IMAGE"

  # Get random image
  random

  debug "main: FILE: ${FILE}"

  # Set each image value to wallpaper image
  debug "main: executing: xfconf-query -c xfce4-desktop -p ${IMAGE} -s ${FILE}"
  xfconf-query -c xfce4-desktop -p ${IMAGE} -s ${WALLPAPERDIR}/${FILE}

done

